### ISSUE TITLE
Add bolt plan snippet

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-editor-services#105]
Provide similar snippets for bolt plans as we do for puppet dsl

**Comment by glennsarti** [comment]
Needs an additional when statement in https://github.com/lingua-pupuli/puppet-editor-services/blob/master/lib/puppet-languageserver/manifest/completion_provider.rb#L225-L231

**Comment by jpogran** [comment]
Closing as need more context or information to scope work
