### ISSUE TITLE
Puppet-Lint warnings/errors show as hints

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#189]
Using the following manifest

```
class bad_formatting {
  user { 'username':
    ensure => absent,
    auth_membership => 'false',
  }
}
```

The puppet-lint checks do not show correctly

![image](https://user-images.githubusercontent.com/5819622/65479294-6f5d0e00-debf-11e9-8f75-ffda34a6608f.png)

The Language Server debug log shows:

```
, [2019-09-24T11:31:04.836536 #42384]  INFO -- : Received textDocument/didChange notification.
D, [2019-09-24T11:31:04.847963 #42384] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///c%3A/Source/puppet-vscode-files/formatting.pp","diagnostics":[{"range":{"start":{"character":0,"line":0},"end":{"character":0,"line":0}},"message":"class not documented","source":"Puppet","code":"documentation","severity":2},{"range":{"start":{"character":23,"line":3},"end":{"character":28,"line":3}},"message":"quoted boolean value found","source":"Puppet","code":"quoted_booleans","severity":4},{"range":{"start":{"character":11,"line":2},"end":{"character":13,"line":2}},"message":"indentation of => is not properly aligned (expected in column 21, but found it in column 12)","source":"Puppet","code":"arrow_alignment","severity":4}]}}
```

The "missing" checks are being sent as Severity 4 (i.e. a Hint), not a warning or error.

It appears something has changed in puppet-lint for https://github.com/lingua-pupuli/puppet-editor-services/blob/78bb4b108ed70b72ae48c08b56232579af36b92b/lib/puppet-languageserver/manifest/validation_provider.rb#L64-L71

**Comment by glennsarti** [comment]
Hrmmm ..... restarting the Language Sever "fixed it".  More investigation required...

**Comment by glennsarti** [comment]
Might be triggered Ctrl-Zing after doing a Format-Document command ...

**Comment by jpogran** [comment]
Closing as need more context or information to scope work

**Comment by glennsarti** [comment]
Found the problem.  PuppetLint.configuration.fix doesn't get reset to `false` after a Format Document call.  So everything after that comes in as `:fixed` problem kind, not `:warning` or `:error`
