### ISSUE TITLE
[Feature] Create Changelog validator script.

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#212]
Creating the changelog is a manual process, we should create a quick validation script that finds any missing Pull Requests that have been merged, but has a missing Changelog entry. To assist in the release process.

Note - Automating the changelog is not a great idea, verification is.

**Comment by jpogran** [comment]
Closing as we can get more value from improving our processes or having been controls on pull requests merges than spending time on tooling
