### ISSUE TITLE
Replace contributing.md and code_of_conduct

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-editor-services#237]
Should this CODE_OF_CONDUCT.md be replaced by https://github.com/puppetlabs/.github/blob/master/CODE_OF_CONDUCT.md ?

(there's also a CONTRIBUTING.md, but I'm not so sure about that one)

_Originally posted by @DavidS in https://github.com/puppetlabs/puppet-editor-services/pull/236_

**Comment by jpogran** [comment]
The original CONTRIBUTING.md and CODE_OF_CONDUCT.mt came directly from Github suggestions, back when we were hosted in the Lingua org. They served as a good starting point for small projects.

Adopting the ones in the Puppet Github organization would bring us in line with company standards. In order to do this, according to https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization, we would have to remove each file from our repo in order for the Puppet ones to show up. 

After looking at a few Puppet repos, this doesn't seem to be followed everywhere and most have local versions and some differ from the Puppet namespace.

**Comment by binford2k** [comment]
fwiw, the `.github` repo is relatively new. Most pre-existing repositories haven't been switched over to use it.
