### ISSUE TITLE
Revert Facter 4.0.17 path when FACT-2562 is completed

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/puppet-editor-services#240]
@jpogran We should probably merge this (test now pass) and then possibly revert once Facter 4.0.17 is released with a fix.  Until then all CI pipelines for this project will fail.

_Originally posted by @glennsarti in https://github.com/puppetlabs/puppet-editor-services/pull/239#issuecomment-615005838_

**Comment by IrimieBogdan** [comment]
@jpogran Facter [4.0.17](https://rubygems.org/gems/facter/versions/4.0.17) was released on rubygems, please give it a try.
