### ISSUE TITLE
Refactor facts request

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#245]
## Describe the Bug
In https://github.com/puppetlabs/puppet-editor-services/pull/243 the message handler calls out the sidecar to run Facter on every invocation, however this is quite slow.  Instead it should use the already cached facts from the object cache

1. Create tests for the output of `puppet/getfacts`
2. Remove the `fact_all` sidecar command
3. Use the object cache for the facts

**Comment by jpogran** [comment]
Removed the bug label and labeled it as enhancement, as it *is* working....just slowly. :)
