### ISSUE TITLE
Add autocomplete for forge modules in Puppetfile

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#254]
## Use Case
When typing a partial module name in a Puppetfile, it would be nice if autocomplete could be invoked to complete the rest of the name

## Additional Context
From https://github.com/puppetlabs/puppet-editor-services/issues/28

**Comment by jpogran** [comment]
This was completed client side in https://github.com/puppetlabs/puppet-vscode/issues/709
