### ISSUE TITLE
Do we need to worry about non-file based documents?

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#27]
https://code.visualstudio.com/docs/extensionAPI/document-selectors

> Not all text documents are stored on disk, for example, newly created documents. Unless specified, a 
> document selector applies to all document types. Use the DocumentFilter scheme property to narrow 
> down on certain schemes, for example { scheme: 'file', language: 'typescript' } for TypeScript files that 
> are stored on disk.

Should try the Puppet extension with https://marketplace.visualstudio.com/items?itemName=jrieken.vscode-memfs

**Comment by jpogran** [comment]
We set scheme to file in the client, so this can be closed
