### ISSUE TITLE
DOS-like line endings in release executables

### ISSUE THREAD

**Issue by williamboman** [puppetlabs/puppet-editor-services#318]
## Describe the Bug
Starting in the 1.3.0 release, it seems like the bundled executables come with DOS-like line endings. This causes some issues when running on POSIX systems, for example interpreting the shebang incorrectly:

```
$ ./puppet-languageserver
env: ruby\r: No such file or directory
```

## Expected Behavior
Unix-like line endings!

## Steps to Reproduce
1. Go to https://github.com/puppetlabs/puppet-editor-services/releases
2. Download the either the .zip or .tar.gz from the 1.3.0 release.
3. Unpack the archive.
3. Review the line endings of the `puppet-*` scripts.

## Environment
 - Version: 1.3.0
 - Platform: macOS

**Comment by dpmmb** [comment]
As a work-around you can run dos2unix or similar on puppet-languageserver.

**Comment by bit0rez** [comment]
I have the same problem.
Looks like bug in `$LOAD_PATH` for dependencies.
This is reproduced when I using a link to `puppet-languageserver` instead of starting it from the installation directory.

**Comment by williamboman** [comment]
Seems fine now :+1:
